//define store name and push it to the DOM in the top title
const first_name = "Sal";
const last_name = "Aurigemma's";
const store_name="Sal";//kept from earlier instructions, could replace with first_name
//create variables to push to the DOM for current year and time

 // Manipulate the header to display your name with formatting
 const firstNameSpan = document.getElementById('first_name_span');
 const lastNameSpan = document.getElementById('last_name_span');
 firstNameSpan.textContent = first_name;
 lastNameSpan.textContent = last_name;

top_title.innerHTML=("Used Smart Phone Store");

//initialize hits and spins and send to the DOM
let hits= 0;
let spins=0;
//let wins;
let over_half=false;
hits_span.innerHTML = hits; 
spins_span.innerHTML = spins;


//this is the code for POKE8. Start by defining the items, prices, images
let name1 = "HTC";
let price1 = 40.00;
let image1 = "images/HTC.jpg";

let name2 = "Apple";
let price2 = 75.00;
let image2 = "images/iphone-3gs.jpg";

let name3 = "Nokia";
let price3 = 35.00;
let image3 = "images/Nokia.jpg";

let name4 = "Samsung";
let price4 = 45.00;
let image4 = "images/Samsung.jpg";

let name5 = "Blackberry";
let price5 = 10.00;
let image5 = "images/Blackberry.jpg";
/* 
You are required to use a for loop to dynamically create the web page output.What else do you need to do?
1. in the html, cut out all the sections from main. Leave main since we have css to format the page
2. the challengs is this... how do you put html generated by the loop into the correct location under main? You need to use document.querySelector('.main'); it is used to select and reference the HTML element with the class name main. In this case, it's selecting the <main> element with the class="main" attribute from your HTML document.
-- The purpose of this line of code is to target the specific HTML element where you want to add the dynamically generated content. In your code, you are dynamically creating HTML sections for the items in a loop, and you want to insert these sections into the <main> element with the class main so that they appear on your webpage.
--Once you have a reference to this <main> element using document.querySelector('.main'), you can use it to manipulate its innerHTML property by appending or inserting HTML content dynamically. This allows you to add the generated item sections to your webpage within the specified <main> element.
-- document.querySelector('.main').innerHTML += `
--- selects the innerHTML of main and then the ` allows you to execute the string template
3. replicate the <section ...> information from the orginal html in the loop so your onclick and on mouseovers still work
4. use string templates to send name to the DOM:  ${eval("name"+i)}; same goes for price and image
*/
for (let i=1; eval("typeof name"+i) != 'undefined'; i++) {
    document.querySelector('.main').innerHTML += `
        <section class="item" onmouseover="changeClassName(this);" onclick="resetClassName(this);">
            <h2>${eval("name" + i)}</h2>
            <p>$${eval("price" + i)}</p>
            <img src="${eval("image" + i)}" />
        </section>`;
}

//send store name info to the footer title
bottom_title.innerHTML=("Your one stop shop for used phones - "+store_name+"'s");            
//send store name info to the footer title

const currentYear = new Date().getFullYear();
const currentTime = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

//create an html template for the footer table, using backtic instead of quotes
/* This HTML table represents a footer section with key information. It includes a header cell with stylized text, followed by rows containing copyright details, the current year, and the current time. Dynamic values are inserted using JavaScript variables for a personalized and up-to-date footer. */
const footerTable = `
    <table>
        <tr>
            <td></td>
            <td class="table-header">Your One Stop For Used Phones - ${first_name.charAt(0).toUpperCase()}.${last_name.charAt(0).toUpperCase()}'s</td>
        </tr>
        <tr>
            <td>1.</td>
            <td>Copyright @ ${first_name} ${last_name}</td>
        </tr>
        <tr>
            <td>2.</td>
            <td>${currentYear}</td>
        </tr>
        <tr>
            <td>3.</td>
            <td>${currentTime}</td>
        </tr>
    </table>
`;

// Set the innerHTML of the bottom_title element to the generated table
bottom_title.innerHTML = footerTable;

//this should be two functions or more but... it changes the item name to rotate for the images and updates the spin count and calculates hits/spins ratio, sending both to the DOM
function changeClassName(element) {
    if(element.className=='item'){
        spins=spins+1;
        element.className = 'item rotate';
    } 
        
    //spins=spins+1; 
    if(spins<2*hits&&hits<spins){
        //wins=true;
        over_half=true;
    } else {
        //wins=false;
    }
    //win_span.innerHTML=wins;
    win_span.innerHTML=over_half;
    spins_span.innerHTML = spins; 
    hit_spin_span.innerHTML=(hits/spins).toFixed(2);
}

//this should be two functions or more but... it changes the item name by removing the rotate for the images and updates the hits count and calculates hits/spins ratio, sending both to the DOM
function resetClassName(element) {
    if(element.className=='item rotate'){
        hits=hits+=2; 
        element.className = 'item';
    } else {
        changeClassName(element);
    }
        
    if(spins<2*hits&&hits<spins){
        //wins=true;
        over_half=true;
    } else {
        //wins=false;
    }
    //win_span.innerHTML=wins;
    
    win_span.innerHTML=over_half;
    hits_span.innerHTML = hits; 
    hit_spin_span.innerHTML=(hits_span.innerHTML/spins_span.innerHTML).toFixed(2);
}



    